# Generated by Django 5.2.6 on 2026-01-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='reading_audio/')),
                ('expected_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField()),
                ('accuracy_score', models.IntegerField()),
                ('mispronunciations', models.JSONField(default=list)),
                ('risk_score', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('transcribed_text', models.TextField(blank=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reading_analysis.readingsession')),
            ],
        ),
    ]
