# Generated by Django 5.2.6 on 2026-01-17 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_question_game_data_question_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('key_insights', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('reading_recommendation', models.TextField()),
                ('math_recommendation', models.TextField()),
                ('focus_recommendation', models.TextField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cache', to='assessment.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_caches', to='assessment.user')),
            ],
            options={
                'db_table': 'dashboard_cache',
                'indexes': [models.Index(fields=['session'], name='dashboard_c_session_51e942_idx'), models.Index(fields=['user', 'cached_at'], name='dashboard_c_user_id_c1cc99_idx')],
            },
        ),
    ]
